apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:srkH2zTVsOz92noaIGd8dSLSW5lDybTWvPuEn5AljRGj6Gb74vqjYw==,iv:X2ujfT8yaEB8xHYH7tkWW3yLWj7mg/Sr+2qdL6hqAXQ=,tag:0rpCmr4PBayC6KfXEJD8mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fvykmq7ss8uxgyrejk4upavvytv4jxkm05n06778cdqhp2xq8vfsc2cnc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN0VvSEp5YXQwWklLRkFH
            bjRqMHlLTGdwbzJDTWJCdTZhMnVPVGE1NmkwCkticXhPZ3Rhc1F5T2Z3bVBYTmJ0
            OExkMnRvRHp4OGlNOUp6V3plWFJtUE0KLS0tIE9kTTRaKzlxdGlabStXeDFjZzdx
            M0FoSFR0SkhTK2w5QXQ4L2hZWjlzVWcKyUlVtSFn6xEFWZ9vZGwQ7XFDYO1BrVnd
            Onj81FV62TWJ+w6RalE7MhyUQBBVvNShJc7lQwwoPo1YQXRvsW6xyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T05:56:07Z"
    mac: ENC[AES256_GCM,data:gR0BfXSNqdfm0+sK6qIztoLznq7HzNtKZWaMz/Mb9jaBqZ6j7B1bdtlPyHYnd63bShYmlomQlIgXS3sqYL1u/mid+EzezF84+YIvgcO6NwcQZg80N2cWuUP0bHXHnkgB6DSr5vhkAGasaHwLs/13LmDzsFS4Kd99ysD80MX3DLE=,iv:nZTZNZmdNF4CjuaRqTOiaRzpPHGlUXsG1GjYQxUMC7s=,tag:1yirirncXTkxfqhwHCyjEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
