apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BeCml3iVFnQCdJU857YXOzw2b3Zjf98PyVXwUI9X5VjnpmxezFyPBA==,iv:O7UNYFgadeW0MfG993+d85r/32HC5CPjsZNJWLoSUgE=,tag:VHViB/o3HZUPIA8NvNBiyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fvykmq7ss8uxgyrejk4upavvytv4jxkm05n06778cdqhp2xq8vfsc2cnc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR3hUeHRyNnNaNFdPbk1o
            N1VjYWlWbGlQRHo3ZkoyUkhUeXhiMUJCOWpVCmliUkJ1dXRxQ0JRSUs3VFdRYTU0
            ZDV2YjVPVm9FMjZZb0doVGhVSnJXdkkKLS0tIHl2V0tnQm50bFJWQVZTWEZKejFr
            cWprTTNHT3g2Qk9YVHZVOUdWQnoyOEkKbB8jGrd9C+0fhHeA6rLXzpSAUTOj4vIp
            Fzt5e81OzECrPJMHr3HzHr7LccfnMd7NwkFfLiHFidLkIFVamUzgNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T06:16:58Z"
    mac: ENC[AES256_GCM,data:sVOFTHZWvxwfqqeuRaPCc/lvfircGKI45jCV7EE+/baQ4EmmbVKZ7lso56fPIBpkzX77W3WSwYE+SUuEiT4mn7gInEsjBdnssRGLEEPQ86p1XEQkA68jorR2oR4rlZ0K0P/Geop2diKt908Ok0pjCVTQmTfKmeYWogyT53pC4f8=,iv:ZF+nzMOrXEYKkPl9km3AsygvEQwZrrg3zgoU52BTmt4=,tag:UDxA5dIwSPXqzQGM86pBEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
