apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gwB24ff1v4+WFffP1mhOVJoeJDMXEw==,iv:oVg+q/MuQ0quS9K3FGbzbdz2wON4Qju85J7Ghzsk2FE=,tag:PBK0RXeb8k0wo+JSxc4+sg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yjipaCyj5P+RQfj4lCxUhemjOA==,iv:rx1eeAGLIZSFRqoK54tuGuZENS82UlMT+xLBYPQ7gYM=,tag:lJ8ftRR2rtSzFYXX7kmAPg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pIt54zrWqKg32N0Ceos16rZLiwVPdXe8J7ccux1nIWspZ6Bn,iv:oEfNBO8zcLqzjkmGr22g/EdCULGw1c92VXhQmqudvhU=,tag:PGzsQ1fvClsoWfjfXPaOjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fvykmq7ss8uxgyrejk4upavvytv4jxkm05n06778cdqhp2xq8vfsc2cnc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVG4vTU9xaWJQeE5TdmNT
            d1laS1VBR1NLRnJOL1ZwRlhHc01QWjFNeWx3CjdoSWlIUmJ6c2JGRDVLSEJUVTZQ
            MU5CalZ2T0U1OTdycFhMSWZaNkcwLzAKLS0tIFhZdUN0MDRNYzVZcWUvdXhzdmhO
            WmxoU2lldm5lV2F2eFlpM3FzWHBYUWcK6+1ggyc1xvlDCgyALvesx90VzX1MyR1b
            G63y3PyU1bucRCcDsmG7HWaQz70u5c9dX/4UvRdFLkZCvz9ulQo3Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T06:16:58Z"
    mac: ENC[AES256_GCM,data:dIAbUUBYj74u/1MCaAH0xOq1sYH+9GZh/uoSS3gosItD1M/4EDZBUtAa94cRvxqPZh/3JNVCM5Gsn9AmKhxJI2GEWAfDYv4NNmJ/EhiEpNY3jncWEdHvSdBdVgcC8wX6XMHwNi45edcLl+zQz4QXuEwtQvKXC07wtGr16mNLA/Y=,iv:j2FsIKpVhgQzAPSmVkZQcKeFWSfo8OdQVeCOk8InIj4=,tag:m+Cg2HNRnTkL6h8gyAIJFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
