apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:fFpoMm+nC/w5x6XhK+KyDDLlttCH38i1hEG2s2fzNVc=,iv:V/Eu9PhIfJ2iDfIk6AXGEVwNVtc0hZRIC/O5LdVAnL0=,tag:Dkq+lcu0aCCFUwzdf/JN2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fvykmq7ss8uxgyrejk4upavvytv4jxkm05n06778cdqhp2xq8vfsc2cnc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYU5FeFJSQXZmSldqWlJa
            cU1NZzg2Vk1ONFhaOWM4aDRxeUlmaCs5Z2x3CnpNamV1ck4vOFFxY0hhdmgzZWJC
            LzRQRGFtVXluZEIyRmRoZTM2SzFiVncKLS0tIDJVQTIwK0dPanhhdlY1TDRFWjVk
            Q1RQZ2RvUHJnUHRzcEszNUI4Yk1kckUKC1r1Hj9rsBjO1p3E5Oj2pOwJvT14fY4I
            e+q9FZdLL75oy/f9bm56hLe84dcXyDKcqJtQQsn0SlF8Ti5sWXUE8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T05:56:07Z"
    mac: ENC[AES256_GCM,data:d4YOt0wa7B/S86cku26dMRI8+SPd3PkOGnH3SRGv2+juoQv0nLfwTarWjmDuScJCUjhpjCgglElpmQywM1w3LZqiT2sU3fFs0mNyJYxVA0q6m9IUdUd8l1fDwZdZqzgCFIU8e/RD1KX73wFxIS10PY0/wsL15ye5/hKbd8Ri62Q=,iv:lZrpkhPhmuUHGhfmahvSuhTSODhbIo4bmUjptNtLMD4=,tag:3wmXRt/GF36t/Euy4Y0e3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
