apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:htwI2AYTdDfB/kmL75exbCYRDrRpEKYpfkpcARi2vkQ7qafom8SarQ==,iv:YX0E0LgBOzuS88TlIWilLeoFGO1QhMSoDU31x/hP58E=,tag:yas80xBYugHiS2n4AtQsPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fvykmq7ss8uxgyrejk4upavvytv4jxkm05n06778cdqhp2xq8vfsc2cnc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUm5oR1NEZVRNL2hkUlFa
            ZCtZUGdoOWg1YmMrb3g0S3dMWmphL3RpM2g4ClVSOVJpNEtMN0duakhwS2dkdkJx
            OElUTE9jLzBTRFpnSDZuVEU5R3RXVnMKLS0tIGNHZkQ3SDdacm11OU9lc21LVWNU
            QUVpanB1dTBwVlVIY2wvR1pURXo0djgK2EHrRqrm4tgqPNZ+1/ccrI8PPV7bvm2k
            I6D7ZdKQB5DMOs9LIHqTvBrmIEuIxQcq7wd16lf04CFTPP5qyXNSOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T05:56:07Z"
    mac: ENC[AES256_GCM,data:O+7d41gHJ/l5KFTZacQeOSiWIH95sy0YUu/6+4+3jw2EjYNhAiUS0kx63CHFF2GePEDrYl8ilnZAKYAGXQfjJLOyMViOwkInidyDxlAHz51xGtyd9Lt6BRmoLbf7GWv6AKEer81336UKadAEpDPazNyBFS4Ztp37iHwuHKp/oP0=,iv:gKDCkNHiuTXKgDHZmdnX8qOcXcH/+zZjUUC4Wldk/zI=,tag:Y5lgL4Gq76BVskNJ6tzOig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
